[package]
name = "hax-lib"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme = "README.md"
description = "Hax-specific helpers for Rust programs"


[target.'cfg(hax)'.dependencies]
num-bigint = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }

[dependencies]
hax-lib-macros = { workspace = true, optional = true }

[features]
default = ["macros"]
macros = ["dep:hax-lib-macros"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hax)'] }
