name: Test JS build

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches: [main]
    
jobs:
  engine-js-build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix build .\#hax-engine.passthru.js -L  
