name: Extract and Run - Coq

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: ⤵ Install hax
        run: |
          nix build .\#check-coq-coverage