name: Rustc coverage tests with negative results, and snapshots verification

on:
    pull_request:
    merge_group:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    rustc-coverage-tests:
      runs-on: linux
  
      steps:
        - uses: actions/checkout@v4
  
        - if: runner.environment == 'github-hosted'
          uses: DeterminateSystems/nix-installer-action@main
        - name: Set up Cachix
          uses: cachix/cachix-action@v15
          with:
            name: fstar-nix-versions
            push: false
      
        - name: ⤵ Install hax
          run: |
            nix profile install .
            nix profile install nixpkgs#rustup
  
        - name: ⤵ Install FStar
          run: nix profile install github:FStarLang/FStar/v2025.02.17

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'

        - name: Install Python dependencies
          uses: py-actions/py-dependency-install@v4
          with:
            path: rustc-coverage-tests/requirements.txt
  
        - name: Run tests with negative checking
          working-directory: rustc-coverage-tests
          run: |
            FSTAR_HOME=~/.nix-profile python3 run-coverage-tests.py all --with-negative --check-stability
