authors:
  franziskus:
    name: Franziskus Kiefer
    description: Creator
    avatar: https://cryspen.com/images/franziskus_hu8239521875621889102.jpg
  lucas:
    name: Lucas Franceschino
    description: Creator
    avatar: https://cryspen.com/images/lucas_hu1387702743353212719.jpg
  maxime:
    name: Maxime Buyse
    description: Engineer
    avatar: https://cryspen.com/images/maxime_hu_8da610acc29fd826.png
    
