{-# LANGUAGE OverloadedStrings #-}

module Test.Deserialize (tests, getAllLlbcTests) where

import Data.Aeson (eitherDecodeFileStrict, eitherDecodeStrict)
import qualified Data.ByteString.Char8 as BS8
import Data.List (isSuffixOf)
import System.Directory (doesFileExist, listDirectory, doesDirectoryExist)
import System.FilePath ((</>), takeExtension)
import Control.Monad (filterM, when)
import Test.Tasty ( testGroup, TestTree )
import Test.Tasty.HUnit
    ( testCase, assertBool, assertEqual, assertFailure, Assertion )

-- Import generated modules
import qualified Generated_Meta as M
import qualified Generated_Values as Val
import qualified Generated_Types as T
import Generated_GAst hiding (Assertion)  -- Hide Assertion to avoid conflict with HUnit's Assertion
import Generated_Krate  -- TranslatedCrate and LlbcFile are here

-- Re-export commonly used types for tests
type FileId = M.FileId
type IntTy = T.IntTy
type FloatType = T.FloatType
type UIntTy = T.UIntTy

tests :: TestTree
tests = testGroup "Deserialization Tests"
  [ testGroup "Basic Type Parsing"
      [ testCase "Parse: FileId from JSON string" test_fileId_parse
      , testCase "Parse: IntTy from JSON string" test_intTy_parse  
      , testCase "Parse: FloatType from JSON string" test_floatType_parse
      , testCase "Parse: UIntTy from JSON string" test_uIntTy_parse
      ]
  , testGroup "LLBC File Deserialization" 
      [ testCase "Find test LLBC files" test_find_llbc_files
      -- Note: The comprehensive LLBC tests will be added dynamically below
      ]
  ]

-- Test parsing basic types from JSON
test_fileId_parse :: Assertion
test_fileId_parse = do
  let json = BS8.pack "0"
  let result = eitherDecodeStrict json :: Either String FileId
  case result of
    Left err -> assertFailure $ "Failed to parse FileId: " ++ err
    Right (M.FileId fileIdVal) -> assertEqual "FileId value" 0 fileIdVal

test_intTy_parse :: Assertion
test_intTy_parse = do
  let json = BS8.pack "\"I32\""
  let result = eitherDecodeStrict json :: Either String IntTy
  case result of
    Left err -> assertFailure $ "Failed to parse IntTy: " ++ err
    Right intTy -> assertEqual "IntTy value" T.I32 intTy

test_floatType_parse :: Assertion
test_floatType_parse = do
  let json = BS8.pack "\"F64\""
  let result = eitherDecodeStrict json :: Either String FloatType
  case result of
    Left err -> assertFailure $ "Failed to parse FloatType: " ++ err
    Right floatType -> assertEqual "FloatType value" T.F64 floatType

test_uIntTy_parse :: Assertion
test_uIntTy_parse = do
  let json = BS8.pack "\"U8\""
  let result = eitherDecodeStrict json :: Either String UIntTy
  case result of
    Left err -> assertFailure $ "Failed to parse UIntTy: " ++ err
    Right uIntTy -> assertEqual "UIntTy value" T.U8 uIntTy

-- Test that we can find LLBC files (optional - files not checked in)
test_find_llbc_files :: Assertion
test_find_llbc_files = do
  let testDir = "../charon/tests/ui"
  dirExists <- doesDirectoryExist testDir
  when dirExists $ do
    llbcFiles <- findLlbcFiles testDir
    let fileCount = length llbcFiles
    -- LLBC files are not checked into the repo, they're generated by the test suite
    -- So this test passes even if no files are found
    assertBool ("Checked for LLBC files in " ++ testDir ++ ", found " ++ show fileCount) True

-- Helper function to find all .llbc files in a directory recursively
findLlbcFiles :: FilePath -> IO [FilePath]
findLlbcFiles dir = do
  entries <- listDirectory dir
  let fullPaths = map (dir </>) entries
  files <- filterM doesFileExist fullPaths
  dirs <- filterM doesDirectoryExist fullPaths
  let llbcFiles = filter (\f -> takeExtension f == ".llbc") files
  subLlbcFiles <- concat <$> mapM findLlbcFiles dirs
  return (llbcFiles ++ subLlbcFiles)

-- Function to create a test case for each LLBC file
-- This will be called from Main.hs to generate dynamic tests
-- This tests that we can actually deserialize LLBC files into Haskell AST types
createLlbcTest :: FilePath -> TestTree
createLlbcTest filepath = testCase filepath $ do
  -- Parse the entire LLBC file as an LlbcFile (which contains TranslatedCrate)
  result <- eitherDecodeFileStrict filepath :: IO (Either String LlbcFile)
  case result of
    Left err -> assertFailure $ "Failed to deserialize LLBC file in " ++ filepath ++ ": " ++ err
    Right llbcFile -> do
      let crate = llbcfileTranslated llbcFile
      -- Successfully deserialized the entire crate!
      -- We can validate that it has the expected structure
      let funDeclCount = length (translatedcrateFunDecls crate)
          typeDeclCount = length (translatedcrateTypeDecls crate)
          globalDeclCount = length (translatedcrateGlobalDecls crate)
          traitDeclCount = length (translatedcrateTraitDecls crate)
          traitImplCount = length (translatedcrateTraitImpls crate)
      
      -- For test_crate.llbc, validate exact counts
      if "test_crate.llbc" `isSuffixOf` filepath
        then do
          -- Expected counts for test_crate.llbc
          let expectedFunDecls = 2
              expectedGlobalDecls = 1
              expectedTypeDecls = 0
              expectedTraitDecls = 0
              expectedTraitImpls = 0
          
          -- Assert each count matches the expected value
          assertEqual "Number of FunDecls" expectedFunDecls funDeclCount
          assertEqual "Number of GlobalDecls" expectedGlobalDecls globalDeclCount
          assertEqual "Number of TypeDecls" expectedTypeDecls typeDeclCount
          assertEqual "Number of TraitDecls" expectedTraitDecls traitDeclCount
          assertEqual "Number of TraitImpls" expectedTraitImpls traitImplCount
        else
          -- For other files, just confirm successful deserialization with counts
          assertBool (concat
            [ "Successfully deserialized LLBC file with charon version "
            , llbcfileCharonVersion llbcFile
            , ": crate '"
            , translatedcrateCrateName crate
            , "' with "
            , show funDeclCount, " fun decls, "
            , show typeDeclCount, " type decls, "
            , show globalDeclCount, " global decls, "
            , show traitDeclCount, " trait decls, "
            , show traitImplCount, " trait impls"
            ]) True

-- Export function to get all LLBC test cases
getAllLlbcTests :: IO TestTree
getAllLlbcTests = do
  -- Check for LLBC files in the test data directory
  let testDataDir = "test/data"
  testDataExists <- doesDirectoryExist testDataDir
  testDataFiles <- if testDataExists
    then findLlbcFiles testDataDir
    else return []
  
  -- Check for LLBC files in the UI test directory
  let testDir = "../charon/tests/ui"
  dirExists <- doesDirectoryExist testDir
  uiTestFiles <- if dirExists
    then findLlbcFiles testDir
    else return []
  
  let allFiles = testDataFiles ++ uiTestFiles
  let testCases = map createLlbcTest allFiles
  return $ testGroup "All LLBC Files" testCases


