{-# LANGUAGE OverloadedStrings #-}

module Test.Deserialize (tests, getAllLlbcTests) where

import Data.Aeson (eitherDecodeFileStrict, eitherDecodeStrict)
import qualified Data.ByteString.Char8 as BS8
import System.Directory (doesFileExist, listDirectory, doesDirectoryExist)
import System.FilePath ((</>), takeExtension)
import Control.Monad (filterM, when)
import Test.Tasty ( testGroup, TestTree )
import Test.Tasty.HUnit
    ( testCase, assertBool, assertEqual, assertFailure, Assertion )

-- Import generated modules
import Generated_Meta
import Generated_Values
import Generated_GAst hiding (Assertion)  -- Hide Assertion to avoid conflict with HUnit's Assertion
import Generated_Crate  -- TranslatedCrate and LlbcFile are here

tests :: TestTree
tests = testGroup "Deserialization Tests"
  [ testGroup "Basic Type Parsing"
      [ testCase "Parse: FileId from JSON string" test_fileId_parse
      , testCase "Parse: IntTy from JSON string" test_intTy_parse  
      , testCase "Parse: FloatType from JSON string" test_floatType_parse
      , testCase "Parse: UIntTy from JSON string" test_uIntTy_parse
      ]
  , testGroup "LLBC File Deserialization" 
      [ testCase "Find test LLBC files" test_find_llbc_files
      -- Note: The comprehensive LLBC tests will be added dynamically below
      ]
  ]

-- Test parsing basic types from JSON
test_fileId_parse :: Assertion
test_fileId_parse = do
  let json = BS8.pack "0"
  let result = eitherDecodeStrict json :: Either String FileId
  case result of
    Left err -> assertFailure $ "Failed to parse FileId: " ++ err
    Right (FileId fileIdVal) -> assertEqual "FileId value" 0 fileIdVal

test_intTy_parse :: Assertion
test_intTy_parse = do
  let json = BS8.pack "\"I32\""
  let result = eitherDecodeStrict json :: Either String IntTy
  case result of
    Left err -> assertFailure $ "Failed to parse IntTy: " ++ err
    Right intTy -> assertEqual "IntTy value" I32 intTy

test_floatType_parse :: Assertion
test_floatType_parse = do
  let json = BS8.pack "\"F64\""
  let result = eitherDecodeStrict json :: Either String FloatType
  case result of
    Left err -> assertFailure $ "Failed to parse FloatType: " ++ err
    Right floatType -> assertEqual "FloatType value" F64 floatType

test_uIntTy_parse :: Assertion
test_uIntTy_parse = do
  let json = BS8.pack "\"U8\""
  let result = eitherDecodeStrict json :: Either String UIntTy
  case result of
    Left err -> assertFailure $ "Failed to parse UIntTy: " ++ err
    Right uIntTy -> assertEqual "UIntTy value" U8 uIntTy

-- Test that we can find LLBC files (optional - files not checked in)
test_find_llbc_files :: Assertion
test_find_llbc_files = do
  let testDir = "../charon/tests/ui"
  dirExists <- doesDirectoryExist testDir
  when dirExists $ do
    llbcFiles <- findLlbcFiles testDir
    let fileCount = length llbcFiles
    -- LLBC files are not checked into the repo, they're generated by the test suite
    -- So this test passes even if no files are found
    assertBool ("Checked for LLBC files in " ++ testDir ++ ", found " ++ show fileCount) True

-- Helper function to find all .llbc files in a directory recursively
findLlbcFiles :: FilePath -> IO [FilePath]
findLlbcFiles dir = do
  entries <- listDirectory dir
  let fullPaths = map (dir </>) entries
  files <- filterM doesFileExist fullPaths
  dirs <- filterM doesDirectoryExist fullPaths
  let llbcFiles = filter (\f -> takeExtension f == ".llbc") files
  subLlbcFiles <- concat <$> mapM findLlbcFiles dirs
  return (llbcFiles ++ subLlbcFiles)

-- Function to create a test case for each LLBC file
-- This will be called from Main.hs to generate dynamic tests
-- This tests that we can actually deserialize LLBC files into Haskell AST types
createLlbcTest :: FilePath -> TestTree
createLlbcTest filepath = testCase filepath $ do
  -- Parse the entire LLBC file as an LlbcFile (which contains TranslatedCrate)
  result <- eitherDecodeFileStrict filepath :: IO (Either String LlbcFile)
  case result of
    Left err -> assertFailure $ "Failed to deserialize LLBC file in " ++ filepath ++ ": " ++ err
    Right llbcFile -> do
      let crate = llbcfileTranslated llbcFile
      -- Successfully deserialized the entire crate!
      -- We can validate that it has the expected structure
      let typeDeclCount = length (translatedcrateTypeDecls crate)
          globalDeclCount = length (translatedcrateGlobalDecls crate)
          traitDeclCount = length (translatedcrateTraitDecls crate)
          traitImplCount = length (translatedcrateTraitImpls crate)
      
      -- The test passes if we successfully deserialized the TranslatedCrate
      assertBool (concat
        [ "Successfully deserialized LLBC file with charon version "
        , llbcfileCharonVersion llbcFile
        , ": crate '"
        , translatedcrateCrateName crate
        , "' with "
        , show typeDeclCount, " type decls, "
        , show globalDeclCount, " global decls, "
        , show traitDeclCount, " trait decls, "
        , show traitImplCount, " trait impls"
        ]) True

-- Export function to get all LLBC test cases
getAllLlbcTests :: IO TestTree
getAllLlbcTests = do
  let testDir = "../charon/tests/ui"
  dirExists <- doesDirectoryExist testDir
  if not dirExists
    then return $ testGroup "LLBC Files" []
    else do
      llbcFiles <- findLlbcFiles testDir
      let testCases = map createLlbcTest llbcFiles
      return $ testGroup "All LLBC Files" testCases


