name: Linting for the Rust engine

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clippy
      run: |
        rustup component add clippy
    - name: Run clippy
      run: |
        cargo clippy -p hax-rust-engine -- -D warnings --no-deps
