name: Generate This Month in hax

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *'

jobs:
  generate:
    permissions:
      issues: write
      contents: write
    if: github.repository == 'cryspen/hax'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run script and capture output
        id: run_script
        run: |
          bash .utils/this-month-in-hax-skeleton.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b $(cat this-month-in-hax-branch)
          git add docs/blog
          git commit -m "chore(blog): set up a skeleton for 'This Month in hax'"
          git push --force origin $(cat this-month-in-hax-branch)

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: this-month-in-hax-issue.yml
